### ISSUE TITLE
Размер игрового поля можно установить 0x0px

### ISSUE THREAD

**Issue by ermakof** [centralToNowhere/game-of-life#14]
Действия пользователя:

1. Авторизоваться в приложении
2. Установить Макс. ширина и Макс. высота: равной 0px

ОР: есть ограничение на минимальный размер игрового поля и игровое поле остается в приложении
ФР: размер игрового устанавливается 0x0px и игровое поле исчезает из приложения

Рекомендации:
установить минимальный размер игрового поля

**Comment by centralToNowhere** [comment]
Исправлено  в https://github.com/centralToNowhere/react-otus/commit/430968b9f2f4e9b84093968b021ad9dd6c1397ef - теперь игровое поле должно содержать как минимум одну ячейку, при попытке установить размер поля меньше размера ячейки выводится ошибка валидации соответствующего поля.
Спасибо
