### ISSUE TITLE
Не выводятся правила на экране авторизации

### ISSUE THREAD

**Issue by ermakof** [centralToNowhere/game-of-life#15]
Действия пользователя:

1. Запустить приложение без авторизации

ОР: в левом блоке под надписью Правили есть описание правил
ФР: в левом блоке под надписью Правили нет описания правил

Рекомендации:
либо добавить описание правил либо убрать заголовок Правила

**Comment by centralToNowhere** [comment]
Описание правил добавлено в https://github.com/centralToNowhere/react-otus/pull/13
