### ISSUE TITLE
В форме статистики не выводится информация о количестве кликов и набранных очков

### ISSUE THREAD

**Issue by ermakof** [centralToNowhere/game-of-life#16]
Действия пользователя:

Авторизоваться в приложении

1. Нажать на кнопку Старт
2. Покликать по игровому полю ЛКМ

ОР: в форме Статистика выводится информация о количестве кликов и очков
ФР: в форме Статистика не выводится информация о количестве кликов и очков

Рекомендации:
выводить информацию о количестве кликов и очков или убрать блок статистика

**Comment by centralToNowhere** [comment]
Исправлено - блок статистики удален, вместо него добавлен счетчик поколений
