### ISSUE TITLE
Название окна приложения

### ISSUE THREAD

**Issue by alexanderpono** [centralToNowhere/game-of-life#17]
**Алгоритм воспроизведения:**
- Запустить приложение.
При запуске приложения - название окна браузера содержит название "по умолчанию".

**Ожидаемая реакция:** в названии окна - "Игра "Жизнь" или другая надпись, которая соответствует теме приложения.
**Фактическая реакция:** в названии окна - "Webpack App"

**Comment by centralToNowhere** [comment]
Исправлено
